# Generated by Django 4.1.6 on 2023-10-29 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_processor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='purchasDate',
            new_name='purchaseDate',
        ),
    ]
