version: '3'

services:
  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: pgserver
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "your_email@example.com"
      PGADMIN_DEFAULT_PASSWORD: "your_password"
    ports:
      - "8080:80"  # Map the pgAdmin web interface to port 8080

  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
        - "8000:8000"
    depends_on:
        - postgres_db
    volumes:
        - .:/app
    environment:
        - DBNAME=pgserver
        - DBUSER=pguser
        - DBPASSWORD=root
        - DBHOST=postgres_db
        - DBPORT=5432


volumes:
  pg_data:
